#!/usr/bin/env python3
"""
make_monatomic_ion_2_lt.py — Minimal generator for monatomic ion LT files.

Assumptions:
- This directory handles ONLY monatomic ions (no bonds).
- You keep per-ion parameters in config/ions.yaml.
- Base filename in input_files (without extension) must match the key in ions.yaml.

Behavior:
- For each input_files/*.mol2 -> create lt/<name>.lt
- Required YAML fields: atom_label, mass, charge
- Optional YAML fields: lj.sigma_A, lj.epsilon_kcal
  * If both provided, writes a pair_coeff line.
  * If missing, skips pair_coeff (assume upper-level FF provides it).

Usage:
    python scripts/make_monatomic_ion_2_lt.py 
    # or
    python scripts/make_monatomic_ion_2_lt.py --config config/ions.yaml --in input_files --out lt --overwrite
"""

from __future__ import annotations
import argparse
from pathlib import Path
import sys
import yaml

def load_yaml(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    ions = data.get("ions") or {}
    if not isinstance(ions, dict):
        raise ValueError("Top-level 'ions' must be a mapping in YAML.")
    return ions

def build_lt_text(key: str, entry: dict) -> str:
    # Required fields
    try:
        atom_label = entry["atom_label"]
        mass = float(entry["mass"])
        charge = float(entry["charge"])
    except KeyError as e:
        raise ValueError(f"[{key}] missing required field: {e}")
    except Exception:
        raise ValueError(f"[{key}] mass/charge must be numeric")

    # Optional LJ
    lj = entry.get("lj") or {}
    sigma = lj.get("sigma_A", None)
    epsilon = lj.get("epsilon_kcal", None)
    has_lj = sigma is not None and epsilon is not None

    res = (entry.get("res") or key).replace("/", "_").replace(" ", "_")
    atom_tag = f"@atom:{atom_label}"

    header = (
        f"# Auto-generated by make_monatomic_ion_2_lt.py\n"
        f"# Ion: {key}\n"
        f"# Units: mass [amu], epsilon [kcal/mol], sigma [Angstrom]\n"
    )

    in_settings = ['  write_once("In Settings") {']
    if has_lj:
        sigma_f = float(sigma); epsilon_f = float(epsilon)
        in_settings.append("    # Ensure compatible pair_style is defined in the parent system")
        in_settings.append(f"    pair_coeff {atom_tag} {atom_tag} {epsilon_f:.6f} {sigma_f:.6f}")
    else:
        in_settings.append("    # (Optional) pair_coeff omitted — provided by upper-level force field")
    in_settings.append("  }")

    data_masses = (
        '  write_once("Data Masses") {\n'
        f"    {atom_tag} {mass:.6f}\n"
        "  }"
    )

    data_atoms = (
        '  write("Data Atoms") {\n'
        "    # id   mol   type        charge        x    y    z\n"
        f"    $atom:{atom_label}  $mol:.  {atom_tag}   {charge:.6f}     0.0  0.0  0.0\n"
        "  }"
    )

    body = f"{res} {{\n" + "\n".join(in_settings) + "\n" + data_masses + "\n" + data_atoms + "\n}"
    return header + body + "\n"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", "-c", default="config/ions.yaml")
    ap.add_argument("--in", "-i", dest="in_dir", default="input_files")
    ap.add_argument("--out", "-o", dest="out_dir", default="lt")
    ap.add_argument("--overwrite", action="store_true", help="Overwrite existing LT files")
    args = ap.parse_args()

    cfg_path = Path(args.config).resolve()
    in_dir = Path(args.in_dir).resolve()
    out_dir = Path(args.out_dir).resolve()

    if not cfg_path.exists():
        print(f"[ERROR] config not found: {cfg_path}", file=sys.stderr)
        sys.exit(1)
    if not in_dir.exists():
        print(f"[ERROR] input dir not found: {in_dir}", file=sys.stderr)
        sys.exit(1)
    out_dir.mkdir(parents=True, exist_ok=True)

    ions_cfg = load_yaml(cfg_path)

    # Collect basenames in input_files
    mol2_files = sorted(in_dir.glob("*.mol2"))
    if not mol2_files:
        print("[INFO] No .mol2 files in input_files — nothing to do.")
        sys.exit(0)

    generated, skipped = [], []

    for mol2 in mol2_files:
        key = mol2.stem  # e.g., "K+ion"
        entry = ions_cfg.get(key)
        if entry is None:
            skipped.append((key, "no YAML entry (ions.<key>)"))
            continue

        out_path = out_dir / f"{key}.lt"
        if out_path.exists() and not args.overwrite:
            skipped.append((key, "exists (use --overwrite to regenerate)"))
            continue

        try:
            text = build_lt_text(key, entry)
            out_path.write_text(text, encoding="utf-8")
            generated.append(out_path.name)
        except Exception as e:
            skipped.append((key, str(e)))

    # Summary
    if generated:
        print("✅ Generated LT files:")
        for name in generated:
            print(f"  - {name}")
    if skipped:
        print("⚠️  Skipped:")
        for key, reason in skipped:
            print(f"  - {key}: {reason}")

if __name__ == "__main__":
    main()

