#!/usr/bin/env python3
"""
lt_postprocess.py

Usage:
    python lt_postprocess.py <input.lt.tmp> <output.lt>

This script reads a temporary LT file generated by ltemplify.py,
adds a molecule-specific prefix (e.g., CO2_) to all @atom/@bond/@angle/@dihedral/@improper type tags,
and writes out a clean, modular LT file that follows Moltemplate conventions.

If a YAML file named type_name/<mol>.yaml exists (where <mol> matches the output filename stem),
custom chemical names for atom/bond/angle types will be used instead of generic type1/type2/etc.

In addition, if exist config/charges.yaml directory,
the script will overwrite the atomic charge in the "Data Atoms" section with the value from YAML
**only if the atomtype is present in the YAML**. If not present, it will leave the charge as-is.

- All dihedral_coeff and improper_coeff remain in "In Settings".
- All topology lists are separated into their appropriate write("Data ...") sections.

The prefix is automatically inferred from the output LT file name (e.g., CO2.lt → CO2_).
"""

import sys
import re
import pathlib
import yaml

# --- Argument parsing and input checks ---
if len(sys.argv) != 3:
    sys.exit("Usage: lt_postprocess.py <input.lt.tmp> <output.lt>")

input_lt  = pathlib.Path(sys.argv[1])
output_lt = pathlib.Path(sys.argv[2])

# --- Infer molecule name and prefix from output filename ---
# Example: sulfate.lt → mol = 'sulfate', prefix = 'SULFATE_'
mol    = output_lt.stem
prefix = mol.upper() + "_"

# --- Try to load custom naming from type_name/<mol>.yaml (naming only, not charges) ---
custom_yaml = pathlib.Path(f"type_name/{mol.lower()}.yaml")
custom_map = {}
if custom_yaml.exists():
    with custom_yaml.open("r") as f:
        custom_map = yaml.safe_load(f) or {}

# --- Load charge map only from config/charges.yaml ---
charge_map = {}
config_charge_yaml = pathlib.Path("config/charges.yaml")
if config_charge_yaml.exists():
    with config_charge_yaml.open("r") as f:
        config_charges_all = yaml.safe_load(f)
        if config_charges_all and mol in config_charges_all:
            # charges.yaml must have blocks like: CO2: {CO2_C: 0.700, ...}
            charge_map = {k: float(v) for k, v in config_charges_all[mol].items()}

# --- Read all lines from the input LT file ---
with input_lt.open("r") as fin:
    lines = fin.readlines()

# --- Collect all unique type tags for renaming ---
def collect(pattern):
    "Return a sorted set of all matches to a regex pattern across all lines."
    return sorted({t for l in lines for t in re.findall(pattern, l)})

atom_types     = collect(r'@atom:type\d+')
bond_types     = collect(r'@bond:type\d+')
angle_types    = collect(r'@angle:type\d+')
dihedral_types = collect(r'@dihedral:type\d+')
improper_types = collect(r'@improper:type\d+')

# --- Build replacement maps (default: PREFIX_typeN or custom if YAML provided) ---
def map_or_custom(typemap, kind, custom_map):
    """
    Return a mapping from @kind:typeN → @kind:custom or @kind:PREFIX_typeN.
    kind = 'atom', 'bond', 'angle', etc.
    """
    d = {}
    for t in typemap:
        key = t.split(":")[-1]      # type1, type2, ...
        if custom_map and kind in custom_map and key in custom_map[kind]:
            # Use custom chemical naming from YAML if present
            d[t] = f"@{kind}:{custom_map[kind][key]}"
        else:
            # Otherwise, use default prefix naming
            d[t] = f"@{kind}:{prefix}{key}"
    return d

atom_map     = map_or_custom(atom_types,     "atom",    custom_map)
bond_map     = map_or_custom(bond_types,     "bond",    custom_map)
angle_map    = map_or_custom(angle_types,    "angle",   custom_map)
dihedral_map = map_or_custom(dihedral_types, "dihedral",custom_map)
improper_map = map_or_custom(improper_types, "improper",custom_map)

def replace_all(line: str) -> str:
    """
    Replace all type tags in the line with their prefixed or custom-named versions.
    """
    for mapping in (atom_map, bond_map, angle_map, dihedral_map, improper_map):
        for old, new in mapping.items():
            line = line.replace(old, new)
    return line

# --- Prepare section containers for each Moltemplate block ---
sections = {
    "init":      [],
    "settings":  [],
    "masses":    [],
    "atoms":     [],
    "bonds":     [],
    "angles":    [],
    "dihedrals": [],
    "impropers": []
}

# --- Section flags for parsing state ---
flags = {k: False for k in sections}

# --- Parse the LT file, route lines into section lists after renaming ---
for raw in lines:
    line = replace_all(raw)
    s = raw.strip()

    # Detect section headers and update flags
    if s.startswith('write_once("In Settings")'): flags = {k: False for k in flags}; flags["settings"] = True;   continue
    if s.startswith('write_once("In Init")'):     flags = {k: False for k in flags}; flags["init"] = True;       continue
    if s.startswith('write_once("Data Masses")'): flags = {k: False for k in flags}; flags["masses"] = True;     continue
    if s.startswith('write("Data Atoms")'):       flags = {k: False for k in flags}; flags["atoms"] = True;      continue
    if s.startswith('write("Data Bonds")'):       flags = {k: False for k in flags}; flags["bonds"] = True;      continue
    if s.startswith('write("Data Angles")'):      flags = {k: False for k in flags}; flags["angles"] = True;     continue
    if s.startswith('write("Data Dihedrals")'):   flags = {k: False for k in flags}; flags["dihedrals"] = True;  continue
    if s.startswith('write("Data Impropers")'):   flags = {k: False for k in flags}; flags["impropers"] = True;  continue
    if s == '}': flags = {k: False for k in flags}; continue

    # Append the line to the currently active section
    for key, active in flags.items():
        if active:
            sections[key].append(line)
            break

# --- PATCH: Overwrite charges in Data Atoms section using charge_map (YAML) if available, else keep original ---
if sections["atoms"]:
    cleaned_atoms = []
    for l in sections["atoms"]:
        parts = l.split()
        # Only process lines with at least 7 columns (atom_id, mol_id, atomtype, charge, x, y, z)
        if len(parts) >= 7:
            atomtype = parts[2]  # Should already be mapped, e.g., @atom:CO2_O1
            atomtype_key = atomtype.replace("@atom:", "")
            if atomtype_key in charge_map:
                # Overwrite charge (column 3) if defined in YAML 'charges'
                parts[3] = f"{charge_map[atomtype_key]:.6f}"
        cleaned_atoms.append(" ".join(parts) + "\n")
    sections["atoms"] = cleaned_atoms

# --- Write out the final LT file in Moltemplate syntax ---
with output_lt.open("w") as fout:
    fout.write("import oplsaa2024.lt\n\n")
    # The molecule inherits from OPLSAA, using capitalized name
    fout.write(f"{mol} inherits OPLSAA {{\n\n")

    # Write each Moltemplate section if it is present
    if sections["init"]:
        fout.write('  write_once("In Init") {\n')
        fout.writelines(sections["init"])
        fout.write("  }\n\n")
    if sections["settings"]:
        fout.write('  write_once("In Settings") {\n')
        fout.writelines(sections["settings"])
        fout.write("  }\n\n")
    if sections["masses"]:
        fout.write('  write_once("Data Masses") {\n')
        fout.writelines(sections["masses"])
        fout.write("  }\n\n")
    if sections["atoms"]:
        fout.write('  write("Data Atoms") {\n')
        fout.writelines(sections["atoms"])
        fout.write("  }\n\n")
    if sections["bonds"]:
        fout.write('  write("Data Bonds") {\n')
        fout.writelines(sections["bonds"])
        fout.write("  }\n\n")
    if sections["angles"]:
        fout.write('  write("Data Angles") {\n')
        fout.writelines(sections["angles"])
        fout.write("  }\n\n")
    if sections["dihedrals"]:
        fout.write('  write("Data Dihedrals") {\n')
        fout.writelines(sections["dihedrals"])
        fout.write("  }\n\n")
    if sections["impropers"]:
        fout.write('  write("Data Impropers") {\n')
        fout.writelines(sections["impropers"])
        fout.write("  }\n\n")
    fout.write("}\n")

print(f"   → wrote {output_lt}")

