#!/usr/bin/env python3
"""
lt_postprocess.py

Usage:
    python lt_postprocess.py <input.lt.tmp> <output.lt>

This script reads a temporary LT file generated by ltemplify.py,
adds a molecule-specific prefix (e.g., CO2_) to all @atom/@bond/@angle/@dihedral/@improper type tags,
and writes out a clean, modular LT file that follows Moltemplate conventions.

Behavior:
- type_name YAML is searched under:
    <ROOT>/type_name/<mol>.yaml
    <ROOT>/type_name/<mol.lower()>.yaml
  (exact stem first, then lowercase fallback)

- charges YAML is loaded from:
    <ROOT>/config/charges.yaml

Recommended convention:
- molecules.yaml top-level key   = input .mol2 filename stem exactly
- charges.yaml top-level key     = input .mol2 filename stem exactly
- type_name/*.yaml filename      = lowercase stem (recommended)

If charge/type_name naming is inconsistent only by case, this script tries to recover,
but exact stem matching is preferred for long-term maintenance.
"""

import sys
import re
import pathlib
import yaml

# --- Argument parsing and input checks ---
if len(sys.argv) != 3:
    sys.exit("Usage: lt_postprocess.py <input.lt.tmp> <output.lt>")

input_lt = pathlib.Path(sys.argv[1]).resolve()
output_lt = pathlib.Path(sys.argv[2]).resolve()

if not input_lt.exists():
    sys.exit(f"[ERROR] Input LT file not found: {input_lt}")

# --- Resolve project root using this script location ---
SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
ROOT_DIR = SCRIPT_DIR.parent

# --- Infer molecule name and prefix from output filename ---
# Example: sulfate.lt -> mol = 'sulfate', prefix = 'SULFATE_'
mol = output_lt.stem
prefix = mol.upper() + "_"

# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------
def load_yaml_file(path: pathlib.Path):
    """Load YAML file safely. Return {} if file is empty."""
    with path.open("r") as f:
        data = yaml.safe_load(f)
    return data or {}

def find_type_name_yaml(root_dir: pathlib.Path, mol_name: str):
    """
    Search for type_name YAML in a robust order:
      1) type_name/<mol>.yaml
      2) type_name/<mol.lower()>.yaml
    Return pathlib.Path or None.
    """
    candidates = [
        root_dir / "type_name" / f"{mol_name}.yaml",
        root_dir / "type_name" / f"{mol_name.lower()}.yaml",
    ]

    seen = set()
    unique_candidates = []
    for c in candidates:
        if str(c) not in seen:
            unique_candidates.append(c)
            seen.add(str(c))

    for c in unique_candidates:
        if c.exists():
            return c
    return None

def get_charge_block(all_charge_data: dict, mol_name: str):
    """
    Prefer exact key match in charges.yaml.
    If not found, fall back to case-insensitive match with a warning.
    """
    if not all_charge_data:
        return {}

    if mol_name in all_charge_data:
        return all_charge_data[mol_name] or {}

    for key, value in all_charge_data.items():
        if str(key).lower() == mol_name.lower():
            print(
                f"[WARN] charges.yaml key '{key}' matched '{mol_name}' only case-insensitively. "
                f"Prefer exact stem match.",
                file=sys.stderr,
            )
            return value or {}

    return {}

# ----------------------------------------------------------------------
# Load custom type-name YAML
# ----------------------------------------------------------------------
custom_map = {}
custom_yaml = find_type_name_yaml(ROOT_DIR, mol)

if custom_yaml is not None:
    custom_map = load_yaml_file(custom_yaml)
    print(f"[INFO] Using type-name YAML: {custom_yaml}", file=sys.stderr)
else:
    print(f"[INFO] No type-name YAML found for molecule '{mol}'", file=sys.stderr)

# ----------------------------------------------------------------------
# Load charge map from config/charges.yaml
# ----------------------------------------------------------------------
charge_map = {}
config_charge_yaml = ROOT_DIR / "config" / "charges.yaml"

if config_charge_yaml.exists():
    config_charges_all = load_yaml_file(config_charge_yaml)
    charge_block = get_charge_block(config_charges_all, mol)
    if charge_block:
        charge_map = {str(k): float(v) for k, v in charge_block.items()}
        print(f"[INFO] Using charge overrides for '{mol}' from {config_charge_yaml}", file=sys.stderr)
    else:
        print(f"[INFO] No charge override block found for '{mol}' in {config_charge_yaml}", file=sys.stderr)
else:
    print(f"[INFO] charges.yaml not found: {config_charge_yaml}", file=sys.stderr)

# ----------------------------------------------------------------------
# Read all lines from the input LT file
# ----------------------------------------------------------------------
with input_lt.open("r") as fin:
    lines = fin.readlines()

# ----------------------------------------------------------------------
# Collect all unique type tags for renaming
# ----------------------------------------------------------------------
def collect(pattern):
    """Return a sorted set of all matches to a regex pattern across all lines."""
    return sorted({t for l in lines for t in re.findall(pattern, l)})

atom_types = collect(r'@atom:type\d+')
bond_types = collect(r'@bond:type\d+')
angle_types = collect(r'@angle:type\d+')
dihedral_types = collect(r'@dihedral:type\d+')
improper_types = collect(r'@improper:type\d+')

# ----------------------------------------------------------------------
# Build replacement maps
# ----------------------------------------------------------------------
def map_or_custom(typemap, kind, custom_map):
    """
    Return a mapping from @kind:typeN -> @kind:custom or @kind:PREFIX_typeN.
    kind = 'atom', 'bond', 'angle', etc.
    """
    d = {}
    for t in typemap:
        key = t.split(":")[-1]  # type1, type2, ...
        if custom_map and kind in custom_map and key in custom_map[kind]:
            d[t] = f"@{kind}:{custom_map[kind][key]}"
        else:
            d[t] = f"@{kind}:{prefix}{key}"
    return d

atom_map = map_or_custom(atom_types, "atom", custom_map)
bond_map = map_or_custom(bond_types, "bond", custom_map)
angle_map = map_or_custom(angle_types, "angle", custom_map)
dihedral_map = map_or_custom(dihedral_types, "dihedral", custom_map)
improper_map = map_or_custom(improper_types, "improper", custom_map)

def replace_all(line: str) -> str:
    """Replace all type tags in the line with their prefixed or custom-named versions."""
    for mapping in (atom_map, bond_map, angle_map, dihedral_map, improper_map):
        for old, new in mapping.items():
            line = line.replace(old, new)
    return line

# ----------------------------------------------------------------------
# Prepare section containers
# ----------------------------------------------------------------------
sections = {
    "init": [],
    "settings": [],
    "masses": [],
    "atoms": [],
    "bonds": [],
    "angles": [],
    "dihedrals": [],
    "impropers": [],
}

flags = {k: False for k in sections}

# ----------------------------------------------------------------------
# Parse LT file and route lines into section lists after renaming
# ----------------------------------------------------------------------
for raw in lines:
    line = replace_all(raw)
    s = raw.strip()

    if s.startswith('write_once("In Settings")'):
        flags = {k: False for k in flags}
        flags["settings"] = True
        continue

    if s.startswith('write_once("In Init")'):
        flags = {k: False for k in flags}
        flags["init"] = True
        continue

    if s.startswith('write_once("Data Masses")'):
        flags = {k: False for k in flags}
        flags["masses"] = True
        continue

    if s.startswith('write("Data Atoms")'):
        flags = {k: False for k in flags}
        flags["atoms"] = True
        continue

    if s.startswith('write("Data Bonds")'):
        flags = {k: False for k in flags}
        flags["bonds"] = True
        continue

    if s.startswith('write("Data Angles")'):
        flags = {k: False for k in flags}
        flags["angles"] = True
        continue

    if s.startswith('write("Data Dihedrals")'):
        flags = {k: False for k in flags}
        flags["dihedrals"] = True
        continue

    if s.startswith('write("Data Impropers")'):
        flags = {k: False for k in flags}
        flags["impropers"] = True
        continue

    if s == '}':
        flags = {k: False for k in flags}
        continue

    for key, active in flags.items():
        if active:
            sections[key].append(line)
            break

# ----------------------------------------------------------------------
# Overwrite charges in Data Atoms section using charge_map if available
# ----------------------------------------------------------------------
if sections["atoms"]:
    cleaned_atoms = []
    for l in sections["atoms"]:
        parts = l.split()

        # Typical format: atom_id mol_id atomtype charge x y z
        if len(parts) >= 7:
            atomtype = parts[2]
            atomtype_key = atomtype.replace("@atom:", "")

            if atomtype_key in charge_map:
                parts[3] = f"{charge_map[atomtype_key]:.6f}"

        cleaned_atoms.append(" ".join(parts) + "\n")

    sections["atoms"] = cleaned_atoms

# ----------------------------------------------------------------------
# Write final LT file
# ----------------------------------------------------------------------
output_lt.parent.mkdir(parents=True, exist_ok=True)

with output_lt.open("w") as fout:
    fout.write(f"{mol} {{\n\n")

    if sections["init"]:
        fout.write('  write_once("In Init") {\n')
        fout.writelines(sections["init"])
        fout.write("  }\n\n")

    if sections["settings"]:
        fout.write('  write_once("In Settings") {\n')
        fout.writelines(sections["settings"])
        fout.write("  }\n\n")

    if sections["masses"]:
        fout.write('  write_once("Data Masses") {\n')
        fout.writelines(sections["masses"])
        fout.write("  }\n\n")

    if sections["atoms"]:
        fout.write('  write("Data Atoms") {\n')
        fout.writelines(sections["atoms"])
        fout.write("  }\n\n")

    if sections["bonds"]:
        fout.write('  write("Data Bonds") {\n')
        fout.writelines(sections["bonds"])
        fout.write("  }\n\n")

    if sections["angles"]:
        fout.write('  write("Data Angles") {\n')
        fout.writelines(sections["angles"])
        fout.write("  }\n\n")

    if sections["dihedrals"]:
        fout.write('  write("Data Dihedrals") {\n')
        fout.writelines(sections["dihedrals"])
        fout.write("  }\n\n")

    if sections["impropers"]:
        fout.write('  write("Data Impropers") {\n')
        fout.writelines(sections["impropers"])
        fout.write("  }\n\n")

    fout.write("}\n")

print(f"   → wrote {output_lt}")

