# molecules.yaml
# Molecule system configuration for make_system_lt.py

global:
  xyz_file: "input_files_structure/1_6M_OTFTFE_1_1.xyz"   # Input XYZ coordinates file
  output_lt: "system.lt"                                         # Output LT file name
  extra_imports:
    - "input_files_lt/ff_custom.lt"    # If you want to import external forcefields, use "extra_imports (ff.lt)" (e.g. buckingham potential parameter)

molecules:
  OTF:
    instance_name: OTF
    lt_path: "input_files_lt/OTF-ion.lt"         
    class_name: "OTF-ion"                            
    count_rule: "elem['S']"
    charge: -1      

  Zn_ion:
    instance_name: Zn_ion
    lt_path: "input_files_lt/Zn_ion.lt"             
    class_name: "Zn_ion"                            
    count_rule: "elem['Zn']"                    
    charge: +2

  K_ion:
    instance_name: K_ion
    lt_path: "input_files_lt/K_ion.lt"        
    class_name: "K_ion"                            
    count_rule: "elem['K']"                      
    charge: +1

  TIP3P_2004:
    instance_name: Waters
    lt_path: "input_files_lt/tip3p_2004_oplsaa2024.lt"  
    class_name: "TIP3P"                           
    count_rule: "347"

  TFE:
    instance_name: TFE
    lt_path: "input_files_lt/TFE.lt"         
    class_name: "TFE"                        
    count_rule: "87"            

