# molecules.yaml
# Molecule system configuration for make_system_lt.py

global:
  xyz_file: "input_files_structure/waterTIP3P+methane.xyz"   # Input XYZ coordinates file
  output_lt: "system.lt"                                         # Output LT file name
  extra_imports:
    - "input_files_lt/ff_custom.lt"    # If you want to import external forcefields, use "extra_imports (ff.lt)" (e.g. buckingham potential parameter)

# Typing order of molecules should be same with xyz structure file's molecular order.
molecules:
  TIP3P_water:
    instance_name: water
    lt_path: "input_files_lt/tip3p_2004_oplsaa2024.lt"  
    class_name: "TIP3P"                           
    count_rule: "elem['O']"
    #count_rule: "512" # Also you can explicitly assgin number of waters.

  Methane:
    instance_name: Methane
    lt_path: "input_files_lt/Methane.lt"         
    class_name: "Methane"                        
    count_rule: "elem['C']"
    #count_rule: "27"      

