# molecules.yaml
# Molecule system configuration for make_system_lt.py

global:
  xyz_file: "input_files_structure/Ag_sulfate_CO2_solvated.xyz"   # Input XYZ coordinates file
  output_lt: "system.lt"                                         # Output LT file name

#  extra_imports:
#    - "input_files_lt/ff.lt"    # If you want to import external forcefields, use "extra_imports (ff.lt)" (e.g. buckingham potential parameter)

molecules:
  AgSlab:
    instance_name: Agblock
    lt_path: "input_files_lt_adsorbent/Ag.lt"    # Path to the Ag slab LT file
    class_name: "Ag"                             # The class name defined inside Ag.lt
    adsorbent: true                              # True for slab (special treatment)
    fixed_group: "1:32"                          # Atom ID range for fixing bottom layer (optional)

  CO2:
    instance_name: CO2ads
    lt_path: "input_files_lt/CO2.lt"             # Path to the CO2 LT file
    class_name: "CO2"                            # The class name defined inside CO2.lt
    count_rule: "elem['C']"                      # Python expression: number of C atoms

  TIP3P_2004:
    instance_name: Waters
    lt_path: "input_files_lt/tip3p_2004_oplsaa2024.lt"  # Path to water LT file
    class_name: "TIP3P"                           # Water molecule class name
    # Waters: number of O - (2 × CO2) - (4 × SO4)
    count_rule: "elem['O'] - 2*mol['CO2'] - 4*mol['Sulfate']"

  Sulfate:
    instance_name: SO4
    lt_path: "input_files_lt/sulfate.lt"         # Path to the sulfate LT file
    class_name: "sulfate"                        # The class name defined inside sulfate.lt
    count_rule: "elem['S']"                      # Number of S atoms (each S = one SO4)
    charge: -2                                   # Ion charge (optional, for notes)
