# List of molecules to be processed by the automation script.
# Each key should match the .mol2 filename (without the .mol2 extension).
# For each molecule, specify:
#   res:      Residue name for LigParGen (-r)
#   charge:   Net charge for LigParGen (-c)
#   optimize: Optimization number for LigParGen (-o) / set from 0~3 
#   (Optionally, you can add more keys later if needed.)

molecules:
  CO2:
    res: CO2         # Residue name used in output and for LigParGen.
    charge: 0        # Net charge of CO2 molecule.
    optimize: 0

  sulfate:
    res: SO4         
    charge: -2       
    optimize: 1

  Benzene:
    res: C6H6
    charge: 0
    optimize: 3

  Ethylene:
    res: C2H4
    charge: 0
    optimize: 3

  Methane:
    res: CH4
    charge: 0
    optimize: 3

  Imidodisulfurylfluoride_minus:
    res: Imidodisulfurylfluoride_minus
    charge: -1
    optimize: 2

  1-Butyl-1-methylpyrrolidinium_plus:
    res: 1-Butyl-1-methylpyrrolidinium_plus
    charge: +1
    smiles: "CCCC[N+]1(CCCC1)C"
    optimize: 2

# Example: add more molecules below by copying this pattern.
#  benzene:
#    res: BEN
#    charge: 0
#
#  acetate:
#    res: ACT
#    charge: -1

